[package]
name = "dps310-async"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
defmt = { version = "1.0.1", optional = true }
embedded-hal-async = "1.0.0"

[features]
defmt = ["dep:defmt", "embedded-hal-async/defmt-03"]
